version: '3.7'
networks:
    internal:
        driver: bridge
volumes: 
    postgres-data:
        driver: local
    app:
        driver: local

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgres_python_api:5432/user_api
    networks:
      - internal
    ports:
      - 5000:5000
    volumes:
      - app:/usr/src/app/app
    restart: always

  db:
    container_name: postgres_python_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_api
    image: postgres:latest
    networks:
      - internal
    ports:
      - 5405:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/csv:/var/lib/postgresql/csv