"""empty message

Revision ID: c34557db7f12
Revises: 
Create Date: 2021-05-17 21:21:34.475172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34557db7f12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('user_model',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=False),
                    sa.Column('login', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    
    # ### end Alembic commands ###
    op.bulk_insert(
        user_table,
        [
            {
                'id': 1,
                'name': 'User 1',
                'login': 'user1',
                'email': 'user1@example.com'
            },
            {
                'id': 2,
                'name': 'User 2',
                'login': 'user2',
                'email': 'user2@example.com'
            },
            {
                'id': 3,
                'name': 'User 3',
                'login': 'user3',
                'email': 'user3@example.com'
            },
            {
                'id': 4,
                'name': 'User 4',
                'login': 'user4',
                'email': 'user4@example.com'
            }
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    # ### end Alembic commands ###
